apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: wilqexlabs/mytree_backend:0.3
        ports:
        - name: backend-port
          containerPort: 8080
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: DATABASE_URL
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: JWT_SECRET
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: S3_BUCKET
          - name: S3_ID
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: S3_ID
          - name: S3_REGION
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: S3_REGION
          - name: S3_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: S3_SECRET
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: REDIS_URL
