apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer-service
spec:
  ports:
  - port: 80
    targetPort: backend-port
    protocol: TCP
  selector:
    app: backend
  type: LoadBalancer
