apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: wilqexlabs/mytree_frontend:0.3
        ports:
        - name: frontend-port
          containerPort: 8000
