apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer-service
spec:
  ports:
  - port: 80
    targetPort: frontend-port
    protocol: TCP
  selector:
    app: frontend
  type: LoadBalancer
